### PR TITLE
add verbose logging flag

### PR DESCRIPTION
**Pull request by cdepillabout**
This PR does the following:

- Puts the `glog` library in the `extra-libraries` section instead of the `pkgconfig-depends` section in the cabal file.  `glog` apparently doesn't provide a pkgconfig file :-\
- Adds a verbose logging flag so we have more idea what caffe2 is doing.

### CODE REVIEW

**Comment by cdepillabout** [comment]
update: I've tested that this compiles for the cpu version, but I haven't yet tried it for the gpu version.

**Review by considerate — APPROVED** [review]
The updates to the code look good to me. I this adding support for cudnn though? Shouldn't the title of this PR be changed otherwise?

**Comment by cdepillabout** [comment]
@considerate Good call.  Changed the title.

Also, your old commits are at https://github.com/xc-jp/caffe2-haskell/tree/considerate/cudnn-old so we can pick up adding cudnn support at some point.

**Review by rprije — APPROVED** [review]
LGTM. I haven't tested it and assume you have and it works as intended.

**Pull request merged**
